version: "3"

services:
  web:
    container_name: workout_planner
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=workout_planner.settings
